apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab1
  template:
    metadata:
      labels:
        app: lab1
    spec:
      containers:
      - name: lab1
        image: ghcr.io/aa-130/lab1:sha-5b9473845a3387407b19ffb8b54d8dc337584e33
        ports:
        - containerPort: 80
