apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab1
  template:
    metadata:
      labels:
        app: lab1
    spec:
      containers:
      - name: lab1
        image: ghcr.io/aa-130/lab1:sha-99ba5c2a34b9feaa634e8dae5c12df11f3fca781
        ports:
        - containerPort: 80
