apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab1
  template:
    metadata:
      labels:
        app: lab1
    spec:
      containers:
      - name: lab1
        image: ghcr.io/aa-130/lab1:sha-da364616e263198b6e38f6cb1cf2e067ce9b651a
        ports:
        - containerPort: 80
